services:
  caddy:
    image: caddy-w-cf:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - type: bind
        source: /caddy/Caddyfile
        target: /etc/caddy/Caddyfile

      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
